### ISSUE TITLE
Checking for bugs in the Personal-Portfolio codebase

### ISSUE THREAD

**Issue by jerryowusu** [cynthiainga/Personal-Portfolio#14]
## Please find and resolve the following bugs in your codebase:

1. **worksection.js**
 There is no key value of **'languages'** in the object named **"projects",** kindly change it to **'language'** on **line 251** in order to conform with the key values in the object.

2. **validation.js**
**'label'** is an unused variable at **line 5**, please kindly remove all unused variables from your codebase. Moreover, kindly replace **'document.getElementByIdId'** with **'document.getElementById'** on **line 5** in case you plan to use the **'label'** variable

**Comment by cynthiainga** [comment]
Already fix,thanks Jerry
